// Copyright (C) 2026  OITO2
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package genutil

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// TestGlobalAndPluginOutputPath verifies both output-path helpers place files under the ContextDir subdirectory.
func TestGlobalAndPluginOutputPath(t *testing.T) {
	if got := GlobalOutputPath("/moodle", "AI_CONTEXT.md"); got != filepath.Join("/moodle", ".build82", "AI_CONTEXT.md") {
		t.Errorf("got %q", got)
	}
	if got := PluginOutputPath("/moodle/local/x", "PLUGIN_EVENTS.md"); got != filepath.Join("/moodle/local/x", ".build82", "PLUGIN_EVENTS.md") {
		t.Errorf("got %q", got)
	}
}

// TestSafely_Success verifies a successful result is passed through unchanged.
func TestSafely_Success(t *testing.T) {
	r := Safely("out.md", func() (GeneratorResult, error) {
		return GeneratorResult{File: "out.md", Success: true}, nil
	})
	if !r.Success {
		t.Errorf("expected success, got %+v", r)
	}
}

// TestSafely_Error verifies a returned error becomes a failed result carrying the message.
func TestSafely_Error(t *testing.T) {
	r := Safely("out.md", func() (GeneratorResult, error) {
		return GeneratorResult{}, errors.New("boom")
	})
	if r.Success || r.Error != "boom" || r.File != "out.md" {
		t.Errorf("expected a failed result carrying the error, got %+v", r)
	}
}

// TestSafely_RecoversPanic verifies a panic inside the function becomes a failed result.
func TestSafely_RecoversPanic(t *testing.T) {
	r := Safely("out.md", func() (GeneratorResult, error) {
		panic("something went very wrong")
	})
	if r.Success {
		t.Error("expected Success=false after a recovered panic")
	}
	if r.File != "out.md" {
		t.Errorf("expected File to be the output file even on panic, got %q", r.File)
	}
	if r.Error == "" {
		t.Error("expected a non-empty Error message recovered from the panic")
	}
}

// TestWrite_CreatesParentDirAndMarksCache verifies Write creates missing parent directories and writes the content.
func TestWrite_CreatesParentDirAndMarksCache(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, ".build82", "AI_CONTEXT.md")

	r := Write(target, "hello")
	if !r.Success {
		t.Fatalf("expected success, got %+v", r)
	}
	content, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("expected file to exist: %v", err)
	}
	if string(content) != "hello" {
		t.Errorf("got content %q", content)
	}
}

// TestWrite_ErrorOnUnwritablePath verifies Write reports an error for an invalid path.
func TestWrite_ErrorOnUnwritablePath(t *testing.T) {
	// A path containing a NUL byte is invalid on every OS, so the file operations must fail.
	r := Write(filepath.Join(t.TempDir(), "bad\x00name.md"), "x")
	if r.Success {
		t.Error("expected failure for an invalid path")
	}
	if r.Error == "" {
		t.Error("expected a non-empty error message")
	}
}

// TestHeader verifies the header contains the title, description and a timestamp line.
func TestHeader(t *testing.T) {
	h := Header("Title", "Description")
	if !regexp.MustCompile(`(?m)^# Title$`).MatchString(h) {
		t.Errorf("missing title line: %q", h)
	}
	if !regexp.MustCompile(`(?m)^> Description$`).MatchString(h) {
		t.Errorf("missing description line: %q", h)
	}
	if !regexp.MustCompile(`_Generated by build82 on \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}_`).MatchString(h) {
		t.Errorf("missing/malformed timestamp footer: %q", h)
	}
}

// TestEscapeMdCell verifies pipes are escaped and line breaks are flattened.
func TestEscapeMdCell(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"pipe", "a | b", `a \| b`},
		{"multiple pipes", "|a|b|", `\|a\|b\|`},
		{"lf", "line one\nline two", "line one line two"},
		{"crlf", "line one\r\nline two", "line one line two"},
		{"cr", "line one\rline two", "line one line two"},
		{"pipe and newline combined", "malicious | text\n## Fake Heading", `malicious \| text ## Fake Heading`},
		{"plain text unaffected", "normal display name", "normal display name"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := EscapeMdCell(c.in); got != c.want {
				t.Errorf("EscapeMdCell(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

// TestTimestamp_Format verifies the timestamp matches the expected layout.
func TestTimestamp_Format(t *testing.T) {
	if !regexp.MustCompile(`^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$`).MatchString(Timestamp()) {
		t.Errorf("unexpected timestamp format: %q", Timestamp())
	}
}
