// Copyright (C) 2026  oito2
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package genutil

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/oito2/mcp-build82/internal/cache"
)

// ContextDir is the subdirectory every build82-generated file lives under, relative to a
// Moodle or plugin root — never written directly at the root itself.
const ContextDir = ".build82"

// GlobalOutputPath returns the path for a global (Moodle-root-level) generated file.
func GlobalOutputPath(moodlePath, filename string) string {
	return filepath.Join(moodlePath, ContextDir, filename)
}

// PluginOutputPath returns the path for a per-plugin generated file.
func PluginOutputPath(pluginPath, filename string) string {
	return filepath.Join(pluginPath, ContextDir, filename)
}

// RelativeOrOriginal returns absPath relative to root (slash-separated), falling back to absPath
// unchanged if it can't be made relative (e.g. different volumes on Windows). Used wherever a
// generated Markdown file or a resource error message would otherwise embed an absolute
// filesystem path — which leaks the host's directory structure (and often the OS username baked
// into it) into files meant to travel with the plugin repo and potentially be committed, shared,
// or pasted into a third-party AI chat.
func RelativeOrOriginal(root, absPath string) string {
	if rel, err := filepath.Rel(root, absPath); err == nil {
		return filepath.ToSlash(rel)
	}
	return absPath
}

// GeneratorResult is returned by every generator function — never a panic or a propagated error,
// so orchestrators can run generators in parallel and still produce a complete,
// partial-failure-tolerant report.
type GeneratorResult struct {
	File    string
	Success bool
	Error   string // empty when Success
	Skipped bool   // true when the mtime cache determined regeneration was unnecessary
}

// Safely runs fn, converting any panic into a failed GeneratorResult instead of propagating it —
// this is what lets one broken generator never abort an entire batch.
func Safely(outputFile string, fn func() (GeneratorResult, error)) GeneratorResult {
	result, err := func() (r GeneratorResult, e error) {
		defer func() {
			if p := recover(); p != nil {
				e = fmt.Errorf("%v", p)
			}
		}()
		return fn()
	}()
	if err != nil {
		return GeneratorResult{File: outputFile, Success: false, Error: err.Error()}
	}
	return result
}

// Write writes content to filePath (creating parent directories as needed) and marks it fresh in
// the mtime cache on success.
func Write(filePath, content string) GeneratorResult {
	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		return GeneratorResult{File: filePath, Success: false, Error: err.Error()}
	}
	if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
		return GeneratorResult{File: filePath, Success: false, Error: err.Error()}
	}
	cache.Global.Mark(filePath)
	return GeneratorResult{File: filePath, Success: true}
}

// EscapeMdCell neutralizes Markdown-structure-breaking characters in a value that originates from
// arbitrary plugin PHP (event names, callbacks, DisplayName, ...) before it's interpolated into a
// generated table cell or heading — otherwise an unescaped `|` silently corrupts a table's column
// count, and an embedded newline lets attacker-controlled text open a new Markdown
// section/heading that an AI assistant reading the file as trusted context could mistake for a
// legitimate part of it.
func EscapeMdCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.NewReplacer("\r\n", " ", "\n", " ", "\r", " ").Replace(s)
	return s
}

// Header renders the standard title/description/timestamp header block every generated Markdown
// file starts with.
func Header(title, description string) string {
	return strings.Join([]string{
		"# " + title, "",
		"> " + description, "",
		"_Generated by build82 on " + Timestamp() + "_", "",
		"---", "",
	}, "\n")
}

// Timestamp returns the current UTC time in "2006-01-02 15:04:05" format — always UTC, never
// local time, so generated files are reproducible/diffable across machines in different timezones.
func Timestamp() string {
	return time.Now().UTC().Format("2006-01-02 15:04:05")
}

// PreloadOr generalizes the "if preloaded != nil { x = preloaded.Field } else { x = extract() }"
// pattern.
//
// The nil check is on preloaded itself (the container, e.g. *PreloadedPluginData), never on the
// field get returns — a preloaded field can legitimately be a nil pointer or a zero value
// (e.g. a plugin with no db/tasks.php yields a nil *TasksExtraction from the extractor), and that
// must be trusted as-is rather than triggering a redundant re-extraction. extract is only called
// when preloaded is nil, i.e. when no preload pass happened at all.
func PreloadOr[P, T any](preloaded *P, get func(*P) T, extract func() T) T {
	if preloaded != nil {
		return get(preloaded)
	}
	return extract()
}

// RunCached returns a job function that, when invoked, checks the mtime cache for outputFile
// against sources; if not stale, it appends a Skipped success result to *results, otherwise it
// runs fn and appends fn's actual result. Every append is done under mu, so job functions
// returned by this helper are safe to invoke concurrently against the same *results/mu pair.
func RunCached(results *[]GeneratorResult, mu *sync.Mutex, outputFile string, sources []string, fn func() GeneratorResult) func() {
	return func() {
		if !cache.Global.IsStale(outputFile, sources) {
			mu.Lock()
			*results = append(*results, GeneratorResult{File: outputFile, Success: true, Skipped: true})
			mu.Unlock()
			return
		}
		r := fn()
		mu.Lock()
		*results = append(*results, r)
		mu.Unlock()
	}
}

// WriteTableOrPlaceholder writes header followed by every entry in rows verbatim (each row is
// expected to already include its own trailing newline), or — when rows is empty — a single
// "_(placeholder)_" line instead of a table left with a header and no body rows. header may be
// empty (e.g. GeneratePluginDbTables, where each row already renders its own full table including
// header), in which case only the rows (or the placeholder) are written.
func WriteTableOrPlaceholder(b *strings.Builder, header string, rows []string, placeholder string) {
	if len(rows) == 0 {
		fmt.Fprintf(b, "_(%s)_\n", placeholder)
		return
	}
	if header != "" {
		b.WriteString(header)
	}
	for _, row := range rows {
		b.WriteString(row)
	}
}
